// dossier.mjs — renders a build PLAN into an orderable folder:
//   README.md            overview + how the plan was produced
//   bill-of-materials.md physical parts to order, with prices and links
//   order-list.csv       the same BOM as a spreadsheet you can hand to a cart
//   software-stack.md    every real repo/package to clone/install, per stage
//   build-steps.md       exactly what to do with the parts, in order
//   plan.json            the raw machine-readable plan
//
// This is the "give me a folder with all the parts to order and exactly what to
// build" deliverable, generated from real resolved components.
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { loadRecipes } from './decompose.mjs';

const money = (n) => `$${(Math.round((n || 0) * 100) / 100).toFixed(2)}`;

function recipeFor(plan) {
  if (!plan.decomposition.recipe_file) return null;
  return loadRecipes().find((r) => r._file === plan.decomposition.recipe_file) || null;
}

function readme(plan, recipe) {
  const L = [];
  L.push(`# Build dossier — ${plan.goal}`);
  L.push('');
  L.push(recipe?.summary || 'A buildable plan assembled from real, existing open-source components and orderable parts.');
  L.push('');
  L.push('This folder was generated by **anything-engine**. It decomposed the goal into');
  L.push('subsystems, searched real component sources for each, and assembled the result.');
  L.push('Nothing here is invented: every software pick links to a real repo/package, and');
  L.push('every part links to a real product with a real price.');
  L.push('');
  L.push('## What is in this folder');
  L.push('- `bill-of-materials.md` / `order-list.csv` — the parts to order.');
  L.push('- `software-stack.md` — every repo/package to clone or install, per stage.');
  L.push('- `build-steps.md` — exactly what to do, in order.');
  L.push('- `plan.json` — the raw machine-readable plan.');
  L.push('');
  L.push('## How it decomposed');
  if (plan.decomposition.matched) {
    L.push(`Matched recipe **${plan.decomposition.recipe}** (\`${plan.decomposition.recipe_file}\`), domain: ${plan.decomposition.domain || 'n/a'}.`);
  } else {
    L.push(`No recipe matched. ${plan.decomposition.note || ''}`);
  }
  L.push('');
  L.push('| Stage | Capability | Top pick | Source |');
  L.push('| --- | --- | --- | --- |');
  for (const s of plan.stages) {
    const top = s.picks[0];
    L.push(`| ${s.capability} | ${s.query} | ${top ? top.name : '—'} | ${top ? top.registry : '—'} |`);
  }
  L.push('');
  L.push(`**Estimated parts total: ${money(plan.bom_total_usd)}** (${plan.bom.length} line items). Software is free/open-source.`);
  if (plan.missing.length) {
    L.push('');
    L.push('## Gaps (nothing found — needs a source or a sub-build)');
    for (const m of plan.missing) L.push(`- ${m.capability}`);
  }
  return L.join('\n') + '\n';
}

function bomMd(plan) {
  const L = [];
  L.push(`# Bill of materials — ${plan.goal}`);
  L.push('');
  L.push('Order these. Prices are real 2026 ballparks; check the link for current pricing.');
  L.push('');
  L.push('| Part | For | Qty | Unit | Line | Link |');
  L.push('| --- | --- | --- | ---: | ---: | --- |');
  for (const b of plan.bom) {
    L.push(`| ${b.name} | ${b.capability} | ${b.qty} | ${money(b.unit_usd)} | ${money(b.line_usd)} | ${b.source_url ? `[link](${b.source_url})` : '—'} |`);
  }
  L.push(`| **Required total** | | | | **${money(plan.bom_total_usd)}** | |`);
  if ((plan.optional || []).length) {
    L.push('');
    L.push('## Optional upgrades (not in the total)');
    L.push('');
    L.push('| Part | For | Unit | Link |');
    L.push('| --- | --- | ---: | --- |');
    for (const o of plan.optional) {
      L.push(`| ${o.name} | ${o.capability} | ${money(o.unit_usd)} | ${o.source_url ? `[link](${o.source_url})` : '—'} |`);
    }
  }
  L.push('');
  L.push('_Verified parts are confirmed to exist at a real vendor. Prices vary by region and supplier._');
  return L.join('\n') + '\n';
}

function orderCsv(plan) {
  const rows = [['part', 'for_capability', 'qty', 'unit_usd', 'line_usd', 'link', 'verified']];
  for (const b of plan.bom) {
    rows.push([b.name, b.capability, b.qty, b.unit_usd, b.line_usd, b.source_url, b.verified ? 'yes' : 'no']);
  }
  return rows
    .map((r) => r.map((c) => `"${String(c ?? '').replace(/"/g, '""')}"`).join(','))
    .join('\n') + '\n';
}

function softwareMd(plan) {
  const L = [];
  L.push(`# Software stack — ${plan.goal}`);
  L.push('');
  L.push('Every one of these already exists. Clone or install them.');
  L.push('');
  for (const s of plan.stages) {
    const sw = s.picks.filter((p) => p.kind !== 'part');
    if (!sw.length) continue;
    L.push(`## ${s.capability}`);
    for (const p of sw) {
      const meta = [p.registry, p.license].filter(Boolean).join(', ');
      L.push(`- **${p.name}** — ${p.what || ''}${meta ? ` _(${meta})_` : ''}`);
      if (p.source_url) L.push(`  - ${p.source_url}`);
    }
    // Show the dependency graph of the top pick, if we expanded one.
    if (s.dep_graph && s.dep_graph.count > 1) {
      L.push(`  - _built from ${s.dep_graph.count - 1}+ existing packages (${s.dep_graph.root} dependency graph, depth 1)_`);
    }
    L.push('');
  }
  return L.join('\n') + '\n';
}

function buildStepsMd(plan, recipe) {
  const L = [];
  L.push(`# Build steps — ${plan.goal}`);
  L.push('');
  if (recipe?.build_steps?.length) {
    // Curated, ordered steps from the recipe (the "exactly what to build" part).
    recipe.build_steps.forEach((step, i) => {
      L.push(`## ${i + 1}. ${step.title}`);
      L.push('');
      if (step.detail) L.push(step.detail);
      if (step.uses?.length) {
        L.push('');
        L.push(`Uses: ${step.uses.join(', ')}`);
      }
      L.push('');
    });
  } else {
    // Generic fallback: one step per stage, ordered.
    L.push('Generated from the resolved stages (no curated step list in the recipe):');
    L.push('');
    plan.stages.forEach((s, i) => {
      const top = s.picks[0];
      L.push(`## ${i + 1}. ${s.capability}`);
      L.push('');
      if (top) L.push(`Get **${top.name}** (${top.source_url}). ${top.what || ''}`);
      const parts = s.picks.filter((p) => p.kind === 'part');
      if (parts.length) L.push(`Order: ${parts.map((p) => p.name).join(', ')}.`);
      L.push('');
    });
  }
  if (recipe?.safety) {
    L.push('## Safety');
    L.push('');
    L.push(recipe.safety);
    L.push('');
  }
  return L.join('\n') + '\n';
}

export function writeDossier(plan, outDir) {
  const recipe = recipeFor(plan);
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, 'README.md'), readme(plan, recipe));
  writeFileSync(join(outDir, 'bill-of-materials.md'), bomMd(plan));
  writeFileSync(join(outDir, 'order-list.csv'), orderCsv(plan));
  writeFileSync(join(outDir, 'software-stack.md'), softwareMd(plan));
  writeFileSync(join(outDir, 'build-steps.md'), buildStepsMd(plan, recipe));
  writeFileSync(join(outDir, 'plan.json'), JSON.stringify(plan, null, 2) + '\n');
  return outDir;
}
